DROP TABLE IF EXISTS deposits CASCADE;

DROP TABLE IF EXISTS bonds CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS users_deposits CASCADE;

DROP TABLE IF EXISTS users_bonds CASCADE;